---

- name: Base setup for servers
  hosts: client
  environment:
    PATH: /usr/local/bin:{{ ansible_env.PATH }}

  tasks:
    - import_tasks: tasks/python3.yml
    - import_tasks: tasks/clientapp.yml
