---

  - name: Install system packages
    become: true
    yum:
      name:
        - bzip2-devel
        - bzip2-libs
        - gcc
        - git
        - make
        - openssl-devel
        - openssl-static
        - readline-devel
        - readline-static
        - sqlite-devel
        - zlib-devel
        - python-setuptools
        - python3
        - python3-devel
        - python3-pip
      state: present

  - name: Install virtualenv via pip
    become: true
    become_user: root
    pip:
      name: virtualenv
      executable: pip3

